### ISSUE TITLE
Rec (Maybe :. EltField) rs?

### ISSUE THREAD

**Issue by o1lo01ol1o** [adamConnerSax/Frames-map-reduce#1]
I took an exploratory stab at trying to make some of the combinators in this library polymorphic in the interpretation functor and quickly ran up against the limits of its design.  I imagine it's not straightforward (having run into similar difficulties myself) to to express folds over records where data may be missing.  

Have you given such an implementation any thought?  

The expected functionality, I think, would be something like:
- in the case of a key `a`, use the composite `Maybe a` for grouping.
- in the case of data `as`, if there's `Nothing`, then there's no step, otherwise take the data and step. 

The two sources of difficulty in my mind are constraining the payload through the composed functors and, at the same time, running the fold on the `undistributed` version of the data.

(Separately, it'd also be nice to be able to support `ARec`s as well.)

**Comment by adamConnerSax** [comment]
I'm not sure I quite understand what you mean but I have struggled with ```Maybe :. ElField``` a few times, with mixed success.  So let me restate and see if I understand what you're asking:
 
You have set of records with interpretation functor ```Maybe :. ElField```, likely as a result of loading from file or parsing JSON or whatnot.  

You want to map-reduce that frame using some columns as keys and some as data.  You could just
a. Filter out any rows with any Nothings
b. Fill some nothings with default values and filter the rest.

I assume you've thought of that and neither is good enough.  You'd like to, if I understand correctly,
a. Use ```Maybe a``` as a key- meaning group all ```Nothing``` together and then all ```Just a``` according to `a`?  With the obvious (I think!) extension to multi-column keys?  

But with the data in the reduce step, you'd like to ignore rows with any ```Nothing``` in the data fields? Or perhaps keep it with value ```Nothing```?

For the key, is there an ```Ord``` instance for ```Rec (Maybe :. ElField) rs``` when there's an ```Ord``` instance for the value types?  If not, could we roll a newtyped ```Maybe``` and add the appropriate instances?

For the data part, Hmm.  You want to do the folding when you can and return something that is still ```Rec (Maybe :. ElField)```.  Something like 
```Fold (Rec (Maybe :. ElField) as) [Rec (Maybe :. ElField bs)]```?  
I can imagine writing such a thing as a dimapped version of a 
```Fold (Maybe (Record as)) ([Record bs])```.
Would that work?   If so, I think we could build some bits to simplify all that.

Or am I misunderstanding?

**Comment by o1lo01ol1o** [comment]
> I assume you've thought of that and neither is good enough. You'd like to, if I understand correctly,
a. Use Maybe a as a key- meaning group all Nothing together and then all Just a according to a? With the obvious (I think!) extension to multi-column keys?

Yes, since if `a` has `n` inhabitants on which one would want to group, `Maybe a` gives you another inhabitant on which to group.  Similarly `(Maybe :. ElField) rs` is a product of each `Maybe r` in `rs`.

> But with the data in the reduce step, you'd like to ignore rows with any Nothing in the data fields? Or perhaps keep it with value Nothing?

Yes, this seems to be what, say, `pandas` would conceptually do.  I can imagine some folds where one would want to do something more specialized in the `Nothing` case but I think the general expectation of a user when, say, counting things, would be "don't count it if it's Nothing."

> For the key, is there an Ord instance for Rec (Maybe :. ElField) rs when there's an Ord instance for the value types? If not, could we roll a newtyped Maybe and add the appropriate instances?

Yes, we could assume that the type would have `Ord` or `Hashable` or whatever is needed to group.

> `Fold (Rec (Maybe :. ElField) as) [Rec (Maybe :. ElField bs)]`

I don't quite follow the case where we would take a `Rec (Maybe :. ElField) as` and return `[Rec (Maybe :. ElField bs)]` butI think I might be misunderstanding what step the `Fold` should represent. (Ie, I think we'd only ever have `foldIt :: Rec (Maybe :. ElField) as -> Rec (Maybe :. ElField) as` at a top level if we left the grouping key in the record and `folditShort :: Rec (Maybe :. ElField) as -> Rec (Maybe :. ElField) bs` if we dropped the grouping keys)

Edit:  Also worth clarifying, in the reduction, data should be skipped on a per-column basis, ie, if we have some sparse data and want to calculate some descriptive statistics, we don't want to eliminate a sample from the statistic because there's any data missing, only that, per column, we would not count that sample toward the statistic.  Otherwise, we could just `recMaybe` to get the subset of samples without missing data.

**Comment by adamConnerSax** [comment]
This might just be a notation confusion.  My fold is over the data-part only, since I am assuming it's a post-grouping fold.  And the Control.Foldl library Fold type ```Fold a b``` means a thing to fold a collection of ```a```s into one ```b```. Hence the ```Fold a [b]``` sort of thing.  That really means a function ```Foldable f => f a -> [b]```

Anyway,
I'm assuming you want to do a map-reduce in the style of library.  So you have 
```Rec (Maybe :. ElField) rs```

a. Unpack.  That could be  a no-op in your case, though it seems like there you could also filter out the rows with missing data by creating a filter function that rcasts to the data fields, sequences out the maybe and then tests the result via ```isJust```. Then you would just have rows where all data
is present.  
b. Assign. So choose which columns are keys (say ```ks```) and which are data  (```as```).
c. Reduce. So do some folding over each collection of data in the grouped collection which looks like 
```Traversable f => f (Rec (Maybe :. ElField) ks, f (Rec (Maybe :. ElField) as))```
with a fold ```Fold (Rec (Maybe :. ElField) as) [Rec (Maybe :. ElField) bs]```
So you end up with your map-reduced data
```Traversable f => f (Rec (Maybe :. ElField) ks, [Rec (Maybe :. ElField) bs)]```
which you can then re-assemble to 
```Traversable f => f (Rec (Maybe :. ElField) (ks ++ as))``` if you'd like.  

Is that what you mean?  If those steps all work then the final thing is a fold from your original records to that final Traversable. So:
```Traversable f => Fold (Rec (Maybe :. ElField) rs) (f (Rec (Maybe :. ElField) (ks ++ as)))``` 

Is that what you're after?

**Comment by o1lo01ol1o** [comment]
Yes, that seems correct.

**Comment by adamConnerSax** [comment]
Okay!  So which part of that doesn't work?  
I can imagine each step of that but I've not tried it that way so tell me where it goes awry...

**Comment by o1lo01ol1o** [comment]
Are you suggesting to just re-implement the existing functionality specialized to to types of `Rec (Maybe :. ElField) rs` (en leiu of the currently specialized `Record` type)?

**Comment by adamConnerSax** [comment]
I think so! I hadn't gotten that far. I was trying to make sure I understood what you were after.  But if I understand correctly, then yes, I think it could all be re-implemented for the ```Maybe``` case--or something slightly more general? Though diminishing returns will set in fast there, I think.  
And that could also have some flexibility over what happens to data rows, perhaps roll in some defaulting for some missing fields?  
It would certainly be nice to generalize completely, and I could imagine parts of it:
1. The functor would need to satisfy some constraint allowing the keys to be grouped, I guess just that, one way or another, ``` Ord (Rec f ks)``` or ```(Eq (Rec f ks), Hashable (Rec f ks))```.
2.  There'd have to be some meaningful way to express what it means to fold over a container of ```Rec f as```, which could be as simple as a pair of functions: 
```forall xs.Rec f as -> Maybe (Record as)``` and 
```forall xs. Record bs -> Rec f bs```
That second is easy for any applicative (or, I guess, "pointed") and, for anything traversable, the first amounts to a function ```f (Record as) -> Maybe (Record as)```
And all of that might be worth doing and then specializing to the ```Maybe``` case just so we could handle ```Either``` and various Either-likes?  
What do you think?

**Comment by o1lo01ol1o** [comment]
Ok, right, I was uncertain what the "more general" case would be beyond a couple specialized implementations and a typeclass based API.  

The `Either` cases would be handy to have as well.  

Wouldn't the first function have to be:
`forall xs.Rec f as -> Rec Maybe :. ElField as`? 
 there's no way to guarantee that the fold would provide "all or nothing" with respect to the columns `as`.  
If so, the second would also have to be `forall xs. Rec Maybe :. ElField as -> Rec f as`

**Comment by adamConnerSax** [comment]
True.  You're going for something slightly more general but I think you're right and I can provide my simpler function pair as a special case.

I can try to do all this but probably not until next week or the week after.  Unless you're interested in trying to do it?

**Comment by o1lo01ol1o** [comment]
I'd give the `Rec (Maybe :. ElField) rs` case a shot tonight since I have a use for it and have a little bit of time, do you have an idea of the path of least resistance?

**Comment by adamConnerSax** [comment]
Maybe just try to replicate (a subset) of the stuff in ```MapReduce.hs```?  Starting with just what you need:
1. An unpack that filters rows with missing data, maybe
```unpackGoodData :: (as `Subset` rs) =>  Unpack (Rec (Maybe :. ElField) rs) (Rec (Maybe :. ElField) rs)``` intended to be used with a type application to specify the data cols. That would just be the filter case of unpack with the test involving a recMaybe on the rcast subset.
2. I think the key grouping might just work, at least the ```Ord``` version.  The Hashable version would require a Hashable instance--which might just require one for the empty case but I'm not sure.
3. And then if your fold is just ```Fold (Rec (Maybe :. ElField) as) [Rec (Maybe :. ElField) bs]``` things will just work, right?  You just reassemble like the helpers in Frames.MapReduce do.  And you could add a helper for the case when your folds are just the obvious generalization of a ```Fold (Record as) [Record bs]```

Does that make sense?

**Comment by o1lo01ol1o** [comment]
Closing en lieu of #2
