### ISSUE TITLE
Generalizing over record type and interpretation functor

### ISSUE THREAD

**Issue by adamConnerSax** [adamConnerSax/Frames-map-reduce#3]
cc: @o1lo01ol1o 
I finished rounding out the Maybe stuff you did in https://github.com/adamConnerSax/Frames-map-reduce/pull/2.  It's in the latest commit on master.  I did the minimum required to restore all the functions that were already there in the non-Maybe version. I added 
```haskell
rgetMaybeField
  :: forall t rs
   . (V.KnownField t, F.ElemOf rs t, V.FieldType (V.Fst t) rs ~ V.Snd t)
  => F.Rec (Maybe :. ElField) rs
  -> Maybe (V.Snd t)
rgetMaybeField = fmap V.getField . V.getCompose . V.rgetf (V.Label @(V.Fst t))
``` 

and
```haskell
-- | Control.Foldl helper for filtering Nothings
maybeFold :: FL.Fold a b -> FL.Fold (Maybe a) b
maybeFold (FL.Fold step begin done) = FL.Fold step' begin done
  where step' x ma = maybe x (step x) ma
```
to help and to point the way to generalization.

and made your ```foldAllConstrained``` into ```maybeFoldAllConstrained``` so that I could re-use ```foldAllConstrained``` for the case when the input fold is ```Fold a a``` which is then generalized to ```Fold (Maybe a) (Maybe a)``` via ```fmap Just . maybeFold``` 

If you have a chance to take a look, that would be great.  
Now I'm going to make a branch to try and generalize it all, including the record-type.  If that works, I'll try to re-express these as monomorphizations (is that a word??) of the general thing.

**Comment by adamConnerSax** [comment]
I also added an update of your example which uses the spiffed up ```foldAllConstrained``` to avoid the need to implement ```maybeSum```.

**Comment by adamConnerSax** [comment]
Okay.  I think I've got a record and functor generalized version of the MapReduce part done. See https://github.com/adamConnerSax/Frames-map-reduce/blob/generalizeRecAndF/src/Frames/MapReduce/General.hs

Next I'll try to do the folds.  But after that I could use some help with decisions:

1. I think we should still have modules to just get the ```Record``` and ```Rec (Maybe :. ElField)``` cases since those are so common.  The first will involve some shenanigans of the form ```Rec (Identity :. ElField) rs -> Record rs``` which will be noisy in the source but should be costless performance-wise, I think.   

2. To do the merging of keys and post-reduced data, I need to have ```Rec``` so for those functions, I convert, append, and convert back.  But that is probably a performance nightmare.  So I'm not sure what to do there.  Is there a way to directly append ```ARec``` and ```SRec```? If so, I can make a class and use the efficient method.

3.  There are some naming issues.  Do I name everything the same and then people have to import qualified to use multiple versions?  Or name the general versions differently?

4.  I have instincts but no experience about type-variable order for TypeApplications here. I guess I think that the use cases will often be situations where the compiler can infer the record type and functor from the arguments but you might want to use type applications for subsets.  So I've kept the order with those first (on the functions.  Not always on the classes but those will be used as constraints and won't be inferred anyway, right?)

Anyway, thoughts would be welcome before the complications here overwhelm the ease of use.  That balance always feels tricky...

**Comment by adamConnerSax** [comment]
Did the folds. But was very type-chasing.  
Not enough brain left (or time) to make the monomorphic versions from these.  But I'll try next week.  In the meantime, thoughts are most welcome!  Would this allow you to do what you want to do with ```ARec```?

**Comment by o1lo01ol1o** [comment]
@adamConnerSax 

I just looked over https://github.com/adamConnerSax/Frames-map-reduce/blob/generalizeRecAndF/src/Frames/MapReduce/General.hs, it looks good.  



wrt:

1. If you want, sure.  I don't mind importing qualified in this case since it's likely that you'll be using only (or mostly) that import in any given module.

2. Yea . . .  I'm not sure what to do here, certainly the allocation of a new vector should be avoided if possible; it's part of what makes `ARec` appealing.  If the issue is intermediate structures,  you could return a tuple of `ARec`s in this case and let the user decide the best way to deal with these.  

3.  See 1?

4.  The only thought that occurred to me is that when using the functions, it's likely that the user would need to specify either `f` or the records parameters with more frequency.  (Maybe I'm wrong on the priority, but that's what occurs to me.) I guess time will tell.

> But was very type-chasing.

I bet, in general these HKDs get paid for upfront (but it's really nice when you get a fair bit of milage out of them).

> monomorphic versions from these

I haven't tried to use the polymorphic api in anger yet, but I think there's not a huge rush to the monomorphic versions out.

**Comment by adamConnerSax** [comment]
Thanks for the look!  
1. Yep, importing qualified makes sense to me as well.  
2.  Leaving things as a tuple is pretty much trivial without a helper function.  Maybe I'll add it as a helper in map-reduce-folds.  The version that puts them back together is in Frames-map-reduce because of the Frames specific action of rappend.  I'll just put a big warning on that function.
3. Yeah
4. RIght.  I'm not sure about record vs functor.  For that I just kept them in ```record f``` order since it's the order in which they are used in the types so it's more readable.  If that becomes obviously wrong, I can make a (typeapplications) breaking change or invent new names for things with different type-order.

Agreed that all the type-chasing--and constraint chasing!!--is tedious but usually worth it in the end.

I'll sleep on all this for a bit, redo the monomorphic versions from the general.  I might keep the monomorphic ```Record``` version around in case there is some performance hit for the ```Record (Identity :. ElField)``` version.  I'm hoping I can just coerce.

Then I'll expand the examples a bit,  I guess.

Let me know if you're in need of a hackage release before that.  It could be released like this and then the revamped version after or I can just wait until all that stuff is done.

**Comment by adamConnerSax** [comment]
Okay.  All the maybe bits are now derived from the general bits and are thus record-type-polymorphic.  Onto the Record ones.  I'll keep the originals around, I think, in case we later discover performance issues with the coercions.

**Comment by adamConnerSax** [comment]
Merged and [released](https://hackage.haskell.org/package/Frames-map-reduce) (see https://github.com/adamConnerSax/Frames-map-reduce/pull/4).  Kept the original monomorphic versions as they were--the coercions were as complex as the original code and might've had a performance cost.
